### ISSUE TITLE
streamlined snippets

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#127]
It's confusing having `snippets` and a separate `snippets_library`. It makes more sense to me to have a library of snippets, and a site variable specifying which sub-directory of that library to use for the particular lesson. Otherwise, it's unclear whether best practice is to overwrite `snippets`, which might be accidentally checked-in and merged upstream.

Suggested resolution:

- [x] Move `_extras/snippets_library` to `_includes/snippets_library`
- [x] Move `_includes/snippets` to `_includes/snippets_library/ComputeCanada_Graham_slurm`
- [x] Create a new variable in `_config.yml`:
   ```yml
   snippets: /snippet_library/ComputeCanada_Graham_slurm    
   ```
- [x] Replace all instances of `{% include /snippets/episode_number/snippet.snip %}` with 
   ```
   {% include {{ site.snippets }}/episode_number/snippet.snip %}
   ```

This streamlines the directory structure and may simplify the instructions for setting up a new lesson. It also limits potential damage done when submitting PRs upstream to the config file, rather than the entire snippets directory.

One disadvantage is that Jekyll will build *everything* under `_includes`, so updates to the website may take a little longer. Considering how quickly this builds, this is a minor downside at present.

*Edited for `files` -> `_includes`*

**Comment by psteinb** [comment]
sounds like a superb plan. I like it.

**Comment by tkphd** [comment]
A couple of extras...

- [ ] The snippets are not stand-alone Markdown, but they should be. This would declutter the episode files, and remove some extraneous whitespace.
- [ ] The Jekyll/Liquid variables in `_config.yml` are getting messy. Their current naming scheme, `area_flag_option`, suggests an improvement: convert from a flat structure to a list of (lists of) variables, and call `area.flag.option` instead. Example follows.

```yml
# Existing Structure
---
host_name: "Graham"
host_login: "graham.computecanada.ca"
host_homedir: "/home"
...
sched_name: "SLURM"
sched_submit: "sbatch"
sched_del: "scancel"

# Proposed Structure
- host:
  - name: "Graham"
  - login: "graham.computecanada.ca"
  - homedir: "/home"
  - ...
- sched:
  - name: "SLURM"
  - submit: "sbatch"
  - del: "scancel"
  - ...
```
